package constructor03;

//Write constructor with parameter
//In this case default constructor will not be generated by compiler.
public class Animal {
    public Animal( String name){
        System.out.println(name);
    }
}
